# Generated by Django 4.0 on 2021-12-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resumeapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('graduation', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=100)),
                ('experience', models.FloatField()),
                ('aboutus', models.CharField(max_length=200)),
                ('resume', models.CharField(max_length=500)),
            ],
        ),
    ]
